user: deploy
group: deploy
pid: tmp/pids/thin.pid
timeout: 30
wait: 30
log: log/thin.log
max_conns: 4096
require: []
environment: production
max_persistent_conns: 4096
servers: 3
threaded: true
no-epoll: true
daemonize: true
socket: tmp/sockets/thin.sock
chdir: /u/apps/faye_server/current
tag: faye
