source "http://rubygems.org/"
gem 'faye', '~> 1.0.3'
gem 'thin', '~> 1.6.3'
gem 'faye-redis', '~> 0.2.0'
gem 'capistrano', '~> 3.2.1'
gem 'capistrano-rails', '~> 1.1'
gem 'capistrano-thin', '~> 1.1.0'
gem 'activerecord'
gem 'mysql2'
gem 'pry'
