module AuthToken
  include NodePassword
      def warden
        env['warden']
      end

      def authenticated?
        # check encrypted_password generated by devise
        if (user = User.find_by_username(params[:username])) && user.valid_password?(params[:password])
          @user = user
          return true
        end

        if check_node_username_password
          return true
          # TODO: regenerate encrypted_password using devise
        end

        if check_node_user_id_token
          return true
        end

        # check access_tokens table
        if params[:access_token] && access_token = AccessToken.find_by_token(params[:access_token])
          @user = access_token.user
          true
        else
          false
        end
      end

      def current_user
        warden.user || @user
      end
end
