require 'faye'
require 'faye/redis'
require 'faye/websocket'
require 'active_record'
require 'mysql2'
require 'permessage_deflate'
require 'dotenv'
Dotenv.load
require_relative '../lib/db_connection'
require_relative '../lib/server_auth'
