android_style:
  builder_id: 1
  ring: 1
  vibrate: 1
  clearable: 1
  n_id: 0
jpush:
  id:
  key:
  company_id:
  company_key:
xinge:
  android:
    id:
    key:
  ios:
    id:
    key:
  ios_company:
    id:
    key:
