redis:
  store:
    namespace: catchchat_server_dev
    host: 127.0.0.1
    db: 0
    port: 6379
    driver: hiredis
  cache:
    namespace: catchchat_server_dev:cache
    host: 127.0.0.1
    db: 0
    port: 6379
    driver: hiredis
rate_limit:
  user_login: 5000
  api_request: 5000
