redis:
  store:
    namespace: catchchat_server:store
    host: 127.0.0.1
    db: 0
    port: 6379
    driver: hiredis
  cache:
    namespace: catchchat_server:cache
    host: 127.0.0.1
    db: 0
    port: 6379
    driver: hiredis
  sidekiq:
    namespace: catchchat_server:sidekiq
    host: 127.0.0.1
    db: 0
    port: 6379
    driver: hiredis
rate_limit:
  api_request_without_login:
    limit: 5000
    period: 3600
  api_request_with_login:
    limit: 5000
    period: 3600
ssl_configured: true
