redis:
  store:
    namespace: catchchat_server_staging:store
    host: rails-redis-001.qpdo9q.0001.cnn1.cache.amazonaws.com.cn
    db: 0
    port: 6379
    driver: hiredis
  cache:
    namespace: catchchat_server_staging:cache
    host: rails-redis-001.qpdo9q.0001.cnn1.cache.amazonaws.com.cn
    db: 0
    port: 6379
    driver: hiredis
  sidekiq:
    namespace: catchchat_server_staging:sidekiq
    host: rails-redis-001.qpdo9q.0001.cnn1.cache.amazonaws.com.cn
    db: 0
    port: 6379
    driver: hiredis
rate_limit:
  api_request_without_login:
    limit: 5000
    period: 3600
  api_request_with_login:
    limit: 5000
    period: 3600
ssl_configured: true
