redis:
  store:
    namespace: catchchat_server_test
    host: 127.0.0.1
    db: 0
    port: 6379
    driver: hiredis
  cache:
    namespace: catchchat_server_test:cache
    host: 127.0.0.1
    db: 0
    port: 6379
    driver: hiredis
